// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1697690745);
user_pref("browser.search.region", "KR");
user_pref("calendar.caldav.googleResync", 1697690744);
user_pref("calendar.list.sortOrder", "3685e1c3-9c08-4c94-b339-7f2dae25de4e");
user_pref("calendar.registry.3685e1c3-9c08-4c94-b339-7f2dae25de4e.calendar-main-default", true);
user_pref("calendar.registry.3685e1c3-9c08-4c94-b339-7f2dae25de4e.calendar-main-in-composite", true);
user_pref("calendar.registry.3685e1c3-9c08-4c94-b339-7f2dae25de4e.disabled", true);
user_pref("calendar.registry.3685e1c3-9c08-4c94-b339-7f2dae25de4e.name", "Home");
user_pref("calendar.registry.3685e1c3-9c08-4c94-b339-7f2dae25de4e.type", "storage");
user_pref("calendar.registry.3685e1c3-9c08-4c94-b339-7f2dae25de4e.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1697690753311");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1697690742);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230928194049");
user_pref("extensions.lastAppVersion", "115.3.1");
user_pref("extensions.lastPlatformVersion", "115.3.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"b65ae937-42d0-4ffe-ae58-55de2d7fa39f\",\"google@search.mozilla.org\":\"def3b521-3982-4ae3-a07b-d96c2c82ade9\",\"ddg@search.mozilla.org\":\"dcf92cd6-5900-4266-8a81-de377540e2bc\",\"amazondotcom@search.mozilla.org\":\"9fa62a77-854a-4031-a83c-eabb271049fa\",\"wikipedia@search.mozilla.org\":\"1eb25a93-009e-4d56-bfe1-3588b4112b04\",\"bing@search.mozilla.org\":\"ddac5ffa-6707-4832-8a4c-da9d4eff6c4b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "fa2d3862-1a8d-4e7f-9f7b-22352a1a86c");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.3.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1697690738);
user_pref("toolkit.telemetry.cachedClientID", "9c4e5328-cdc1-490a-8146-f31398d7d46e");
user_pref("toolkit.telemetry.previousBuildID", "20230928194049");
